### ISSUE TITLE
Batch insert error with multi query node in k8s

### ISSUE THREAD

**Issue by zhangbc97** [databendcloud/databend-py#12]
Version:
- databend-query Version: 1.1.29-nightly
- databend-py version: 0.3.9

Deploy method:
kubernetes helm charts
- 3 pods of databend-meta
- 2 pod of databend-query. 
- 1 ClusterIP Service for databend-query

Description:
When execute batch insert, client will upload csv to object storage and then execute `COPY INTO` , and `receive_result` with `query id`.
But the kubernetes Service uses a load balancing strategy, which `receive_result` request maybe send to different query node, and got `http request error: query id not found`

Temporary Solution:
Set Kubernetes Service `sessionAffinity` to `ClientIP`, make all requests made by the same Pod go to the same node, but if use multiprocessing in one pod, all requests will send to single query node.

I have no ideas on how to fix this issue completely,  It seems the `receive_result` request must  be sent to specific query node.

**Comment by hantmac** [comment]
Thanks for your response! I will look into it.

**Comment by hantmac** [comment]
Hi @zhangbc97 , I found the problem is the query id will not be persisted, it is different for each pod.

**Comment by zhangbc97** [comment]
> Hi @zhangbc97 , I found the problem is the query id will not be persisted, it is different for each pod.

Yeah, I agree. There seems to be no way to solve this problem at the client level alone. Perhaps we should set the default `sessionAffinity` of `Service` to `ClientIP` at Helm Chart, or add a feature request to databend-query?

**Comment by zhangbc97** [comment]
set `sessionAffinity` to `ClientIP` will make all request make by one pod sent to same query pod, But that would break the load balancing feature, and horizontal autoscale will be affected

**Comment by zhangbc97** [comment]
Maybe related to  https://github.com/datafuselabs/databend/issues/3889#issue-1106581639 .

**Comment by hantmac** [comment]
> > Hi @zhangbc97 , I found the problem is the query id will not be persisted, it is different for each pod.
> 
> Yeah, I agree. There seems to be no way to solve this problem at the client level alone. Perhaps we should set the default `sessionAffinity` of `Service` to `ClientIP` at Helm Chart, or add a feature request to databend-query?

Using statefulset in helm chart can solve this problem, I will change it to sts or would u like to make a pr ?
