### ISSUE TITLE
duplicated columns when data count greater than 10000

### ISSUE THREAD

**Issue by zhangbc97** [databendcloud/databend-py#31]
### Version
databend_py: 0.4.2
databend_query: 1.1.45-nightly

### Detail
```
import databend_py
conn = databend_py.Client(host='127.0.0.1',port=8000)
columns, data =  conn.execute('SELECT * FROM numbers(10001)',with_column_types=True)
print(columns)
```

columns:
`[('number', 'UInt64'), ('number', 'UInt64')]`
instead of 
`[('number', 'UInt64')]`

When the amount of data exceeds 10000, the data will be returned by paging. function store will append columns multi times

https://github.com/databendcloud/databend-py/blob/6ebf8f11727834eb350cc52f805d815a457a508f/databend_py/result.py#LL44C10-L44C10

**Comment by hantmac** [comment]
Thanks for your report! Have fixed in https://github.com/databendcloud/databend-py/pull/32

**Comment by zhangbc97** [comment]
thanks~
